#!/usr/bin/env bash
set -euo pipefail

TASK_ID=${1:?usage: run_task23_24_v112_historicalvlm_eef_pickfinish50_latest622_1ep.sh TASK_ID}
case "${TASK_ID}" in
  23)
    PICK_SUBTASKS="pick cream,pick popcorn"
    TOL_FILE=task23_eef_open105_pick060_place060_tol_20260718.json
    ANCHOR_FILE=release_anchors_t21_t23_openpick_robotonly.json
    ;;
  24)
    PICK_SUBTASKS="pick cookies,pick popcorn"
    TOL_FILE=task24_eef_open105_pick060_place060_tol_20260718.json
    ANCHOR_FILE=release_anchors_t24_openpick_full_robotonly_fastpick.json
    ;;
  *) echo "unsupported TASK_ID=${TASK_ID}; expected 23 or 24" >&2; exit 2 ;;
esac

PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP=${STAMP:-$(date +%Y%m%d_%H%M%S)}

export MODE=vlm_free
export RUN_ID=${RUN_ID:-mw_orig35999_t${TASK_ID}_v112_historicalvlm_eef_pickfinish50_latest622_${STAMP}}
: "${VLM_CKPT:?set VLM_CKPT}"
export NUM_TRIALS=${NUM_TRIALS:-1}
export SEED=${SEED:-104}
export MAX_STEPS=${MAX_STEPS:-2000}
export REPLAN_STEPS=${REPLAN_STEPS:-5}

# Prompts are always VLM outputs. Official completed stages provide context and
# anti-regression evidence; they never inject a next prompt.
export VLM_COMPLETED_SUBTASKS_MODE=completed_struct
export COMPLETED_UPDATE_FROM_OFFICIAL_STAGE=1
export VLM_HOLD_STATE_HINT=1
export VLM_HOLD_STATE_HINT_PHASE=active
export BLOCK_FORWARD_BEFORE_FIRST_STAGE_DONE=1
export MICROWAVE_STAGE_LOCK_UNTIL_DONE=0
export MICROWAVE_FORWARD_REQUIRE_PRIOR_HOLD=0
export REQUIRE_HOLD_RELEASE_FOR_PICK_FORWARD=1
export REQUIRE_HOLD_RELEASE_FOR_PICK_FORWARD_SUBTASKS="${PICK_SUBTASKS}"
export REQUIRE_HOLD_RELEASE_FOR_PLACE_FORWARD=1
export PREVENT_COMPLETED_STAGE_REGRESSION=1
export PREVENT_HELD_SUBTASK_REGRESSION=1
export PREVENT_RELEASED_HOLD_REGRESSION=0
export PREVENT_SUBTASK_REGRESSION=0
export REGRESSION_GUARD_AFTER_HOLD_RELEASE=0
export FORWARD_SWITCH_BLOCK_PREVIOUS=0
export HOLD_RELEASE_BLOCK_PAST_SUBTASKS=0

export ORACLE_HOLD_RELEASE_NEXT=0
export ORACLE_FORCE_INITIAL_PROMPT=0
export ORACLE_INITIAL_STAGE_LOCK=0
export ORACLE_STAGE_ADVANCE_NEXT=0
export ORACLE_MONOTONIC_SEQUENCE_LOCK=0
export ORACLE_STAGE_LOCK_UNTIL_DONE=0
export REQUIRE_INITIAL_VLM_SUBTASK=0
export STRICT_HOLD_RELEASE_NEXT=${STRICT_HOLD_RELEASE_NEXT:-0}

# Hold decisions are geometric EEF-only. No object-region, lift, gripper, or
# object-moving anchor is permitted.
export ENDPOSE_PLACE_OBJECT_GATE_JSON=
export ENDPOSE_PICK_OBJECT_LIFT_GATE=0
export ENDPOSE_PICK_OBJECT_LIFT_GATE_BY_SUBTASK_JSON='{}'
export ENDPOSE_PICK_HEIGHT_REQUIRE_EEF_NEAR=0
export ENDPOSE_PICK_GRIPPER_GATE=0
export ENDPOSE_PICK_DEFERRED_GRIPPER_RELEASE=0
export ENDPOSE_HOLD_TARGETS_JSON=${ENDPOSE_HOLD_TARGETS_JSON:-${PACK_DIR}/config/tasks2_26_endpose_targets_seed100_199.json}
export ENDPOSE_TARGET_PASSAGE_COUNTS_JSON=${ENDPOSE_TARGET_PASSAGE_COUNTS_JSON:-${PACK_DIR}/config/tasks2_26_target_passage_counts_seed100_199_alltasks_tol045_20260624_074452.json}
export ENDPOSE_HOLD_POS_TOL_BY_SUBTASK_FILE=${ENDPOSE_HOLD_POS_TOL_BY_SUBTASK_FILE:-${PACK_DIR}/config/${TOL_FILE}}
export ENDPOSE_HOLD_RELEASE_MIN_STEPS_BY_SUBTASK_FILE=${PACK_DIR}/config/task23_24_eef_runtime_pickplace_hold30_20260718.json
export ENDPOSE_HOLD_CONSECUTIVE_BY_SUBTASK_JSON='{"open microwave":1,"place cream":3,"place cookies":3,"place popcorn":3}'
export ENDPOSE_HOLD_START_AFTER_RELEASE_ANCHOR=1
export ENDPOSE_HOLD_START_AFTER_RELEASE_ANCHOR_SUBTASKS="${PICK_SUBTASKS}"

export SUBTASK_RELEASE_ANCHORS_JSON=${SUBTASK_RELEASE_ANCHORS_JSON:-${PACK_DIR}/config/${ANCHOR_FILE}}
export INITIAL_SUBTASK_ANCHORS_JSON=
export ALLOW_STAGE_DONE_RELEASE_ANCHOR=0
export ALLOW_AUTONOMOUS_FORWARD_RELEASE_ANCHOR=0
export POST_HOLD_RELEASE_VLA_STEPS=50
export POST_PICK_HOLD_RELEASE_SAME_PROMPT_STEPS=${POST_PICK_HOLD_RELEASE_SAME_PROMPT_STEPS:-50}
export POST_PICK_HOLD_RELEASE_SAME_PROMPT_STEPS_BY_SUBTASK_JSON='{}'
export ENDPOSE_HOLD_AUTO_RESUME_SAME_PROMPT=0
export REQUIRE_OPEN_MICROWAVE_ENDPOSE_HOLD_BEFORE_RELEASE=1
export MICROWAVE_REQUIRE_OPEN_EEF_HOLD_FOR_SUCCESS=1
export MICROWAVE_DEBUG_SAVE_VLM_FRAMES=1
export STOP_ON_STAGE_SUCCESS=1

export REPRO_ENTRY_LAUNCHER=${REPRO_ENTRY_LAUNCHER:-${BASH_SOURCE[0]}}
export REQUIRE_REPRO_SNAPSHOT=0

exec bash "${PACK_DIR}/scripts/run_microwave_eefonly_no_object_gate.sh" "${TASK_ID}"
