#!/usr/bin/env bash
set -euo pipefail

PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
: "${VLM_CKPT:?set VLM_CKPT}"

export MODE=vlm_free
export RUN_ID=${RUN_ID:-task22_v1_latest622_$(date +%Y%m%d_%H%M%S)}
export NUM_TRIALS=${NUM_TRIALS:-1}
export SEED=${SEED:-104}
export MAX_STEPS=${MAX_STEPS:-2000}
export REPLAN_STEPS=${REPLAN_STEPS:-5}

# VLM owns every prompt. The remaining controls are timing-only EEF behavior.
export ORACLE_HOLD_RELEASE_NEXT=0
export ORACLE_FORCE_INITIAL_PROMPT=0
export ORACLE_INITIAL_STAGE_LOCK=0
export ORACLE_STAGE_ADVANCE_NEXT=0
export ORACLE_MONOTONIC_SEQUENCE_LOCK=0
export ORACLE_STAGE_LOCK_UNTIL_DONE=0
export VLM_COMPLETED_SUBTASKS_MODE=off
export COMPLETED_UPDATE_FROM_OFFICIAL_STAGE=0
export VLM_HOLD_STATE_HINT=0
export BLOCK_FORWARD_BEFORE_FIRST_STAGE_DONE=0
export REQUIRE_HOLD_RELEASE_FOR_PICK_FORWARD=0
export REQUIRE_HOLD_RELEASE_FOR_PLACE_FORWARD=0
export MICROWAVE_FORWARD_REQUIRE_PRIOR_HOLD=0
export PREVENT_COMPLETED_STAGE_REGRESSION=0
export PREVENT_SUBTASK_REGRESSION=1
export STOP_ON_STAGE_SUCCESS=1

export ENDPOSE_PLACE_OBJECT_GATE_JSON=
export ENDPOSE_PICK_OBJECT_LIFT_GATE=0
export ENDPOSE_PICK_OBJECT_LIFT_GATE_BY_SUBTASK_JSON='{}'
export ENDPOSE_PICK_HEIGHT_REQUIRE_EEF_NEAR=0
export ENDPOSE_PICK_GRIPPER_GATE=0
export ENDPOSE_PICK_DEFERRED_GRIPPER_RELEASE=0
export ENDPOSE_HOLD_TARGETS_JSON="${PACK_DIR}/config/tasks2_26_endpose_targets_seed100_199.json"
export ENDPOSE_TARGET_PASSAGE_COUNTS_JSON="${PACK_DIR}/config/tasks2_26_target_passage_counts_seed100_199_alltasks_tol045_20260624_074452.json"
export SUBTASK_RELEASE_ANCHORS_JSON="${PACK_DIR}/config/release_anchors_empty.json"
export ENDPOSE_HOLD_POS_TOL=0.08
export ENDPOSE_HOLD_EEF_DEFAULT_TOL=0.08
export ENDPOSE_HOLD_EEF_TOL_CAP=0.24
export POST_HOLD_RELEASE_VLA_STEPS=50
export REQUIRE_OPEN_MICROWAVE_ENDPOSE_HOLD_BEFORE_RELEASE=1
export MICROWAVE_REQUIRE_OPEN_EEF_HOLD_FOR_SUCCESS=1
export MICROWAVE_DEBUG_SAVE_VLM_FRAMES=1
export REPRO_ENTRY_LAUNCHER="${BASH_SOURCE[0]}"

exec bash "${PACK_DIR}/scripts/launch_one_sync_hold_orig35999.sh" 22
