#!/usr/bin/env bash
set -euo pipefail

PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TASK_ID="${TASK_ID:?Set TASK_ID.}"
VLM_CKPT="${VLM_CKPT:?Set VLM_CKPT.}"
EVALUATOR_FILE_OVERRIDE="${EVALUATOR_FILE_OVERRIDE:-}"
PARTITION="${PARTITION:-acd_u}"
NODE="${NODE:-}"
STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)_$$_${RANDOM}}"
SESSION="count_auto_t${TASK_ID}_${STAMP}"
JOB_NAME="count_auto_t${TASK_ID}_${STAMP}"
NUM_TRIALS="${NUM_TRIALS:-2}"
SEED="${SEED:-104}"
VLA_POLICY_SEED="${VLA_POLICY_SEED:-${SEED}}"
VLM_INTERVAL="${VLM_INTERVAL:-5}"
HOLD_AFTER_REQUIRED_STAGES="${HOLD_AFTER_REQUIRED_STAGES:-0}"
STAGE_LATCH_AUTONOMOUS_HOLD="${STAGE_LATCH_AUTONOMOUS_HOLD:-0}"
PROMPT_NO_REGRESSION="${PROMPT_NO_REGRESSION:-0}"
POUR_RETURN_ASSIST="${POUR_RETURN_ASSIST:-0}"
POUR_RETURN_ASSIST_TARGET_RADIUS="${POUR_RETURN_ASSIST_TARGET_RADIUS:-0.20}"
POUR_RETURN_ASSIST_ROTATION_MAGNITUDE="${POUR_RETURN_ASSIST_ROTATION_MAGNITUDE:-0.8}"
POUR_RETURN_ASSIST_MAX_STEPS="${POUR_RETURN_ASSIST_MAX_STEPS:-24}"
TASK10_POUR_RETURN_ASSIST="${TASK10_POUR_RETURN_ASSIST:-0}"
TASK10_POUR_RETURN_ASSIST_TARGET_RADIUS="${TASK10_POUR_RETURN_ASSIST_TARGET_RADIUS:-0.20}"
TASK10_POUR_RETURN_ASSIST_ROTATION_MAGNITUDE="${TASK10_POUR_RETURN_ASSIST_ROTATION_MAGNITUDE:-0.8}"
TASK10_POUR_RETURN_ASSIST_MAX_STEPS="${TASK10_POUR_RETURN_ASSIST_MAX_STEPS:-24}"
ORACLE_TASK8_PICK_AFTER_PLACE_STEPS="${ORACLE_TASK8_PICK_AFTER_PLACE_STEPS:--1}"
REPLAN_STEPS="${REPLAN_STEPS:-5}"
POST_STAGE_STEPS="${POST_STAGE_STEPS:-30}"
PORT="${PORT:-29600}"
RUN_ID="${RUN_ID:-task${TASK_ID}_autonomous_d9f83ac_vla35999_${NUM_TRIALS}ep_${STAMP}}"
RUNS_BASE="${RUNS_BASE:-${PACK_DIR}/runs_autonomous}"
OUT_ROOT="${OUT_ROOT:-${RUNS_BASE}/${RUN_ID}}"
LOG_DIR="${LOG_DIR_OVERRIDE:-${PACK_DIR}/logs_autonomous}"
SUBMIT_LOG="${LOG_DIR}/${JOB_NAME}.log"
RUNTIME_HOME="${RUNTIME_HOME:-${HOME}}"
CPUS_PER_TASK="${CPUS_PER_TASK:-16}"
COUNTING_GUARDED_EVALUATOR="${PACK_DIR}/evaluators/eval_counting_autonomous_guarded_d9f83ac.py"

# These features live in the wrapper, while its base evaluator and scorer stay frozen remote code.
if [[ -z "${EVALUATOR_FILE_OVERRIDE}" && ( "${PROMPT_NO_REGRESSION}" == "1" || "${HOLD_AFTER_REQUIRED_STAGES}" == "1" || "${STAGE_LATCH_AUTONOMOUS_HOLD}" == "1" ) ]]; then
  EVALUATOR_FILE_OVERRIDE="${COUNTING_GUARDED_EVALUATOR}"
fi
if [[ -n "${EVALUATOR_FILE_OVERRIDE}" && ! -f "${EVALUATOR_FILE_OVERRIDE}" ]]; then
  echo "[ERROR] evaluator override is missing: ${EVALUATOR_FILE_OVERRIDE}" >&2
  exit 2
fi
MAX_MEM_PER_CPU_MB="$(scontrol show partition "${PARTITION}" | sed -n 's/.*MaxMemPerCPU=\([0-9][0-9]*\).*/\1/p')"
if [[ -n "${MAX_MEM_PER_CPU_MB}" ]]; then
  MEM_MB="$((CPUS_PER_TASK * MAX_MEM_PER_CPU_MB))"
else
  MEM_MB="${MEM_MB:-240000}"
fi

mkdir -p "${LOG_DIR}" "${RUNS_BASE}"
NODE_ARG=""
if [[ -n "${NODE}" ]]; then
  NODE_ARG="--nodelist=${NODE}"
fi

tmux new-session -d -s "${SESSION}" \
  "bash -lc 'srun -p ${PARTITION} ${NODE_ARG} --gres=gpu:2 -c ${CPUS_PER_TASK} --mem=${MEM_MB}M --job-name=${JOB_NAME} env TASK_ID=${TASK_ID} VLM_CKPT=${VLM_CKPT} EVALUATOR_FILE_OVERRIDE=${EVALUATOR_FILE_OVERRIDE} NUM_TRIALS=${NUM_TRIALS} SEED=${SEED} VLA_POLICY_SEED=${VLA_POLICY_SEED} REPLAN_STEPS=${REPLAN_STEPS} POST_STAGE_STEPS=${POST_STAGE_STEPS} VLM_INTERVAL=${VLM_INTERVAL} HOLD_AFTER_REQUIRED_STAGES=${HOLD_AFTER_REQUIRED_STAGES} STAGE_LATCH_AUTONOMOUS_HOLD=${STAGE_LATCH_AUTONOMOUS_HOLD} PROMPT_NO_REGRESSION=${PROMPT_NO_REGRESSION} POUR_RETURN_ASSIST=${POUR_RETURN_ASSIST} POUR_RETURN_ASSIST_TARGET_RADIUS=${POUR_RETURN_ASSIST_TARGET_RADIUS} POUR_RETURN_ASSIST_ROTATION_MAGNITUDE=${POUR_RETURN_ASSIST_ROTATION_MAGNITUDE} POUR_RETURN_ASSIST_MAX_STEPS=${POUR_RETURN_ASSIST_MAX_STEPS} TASK10_POUR_RETURN_ASSIST=${TASK10_POUR_RETURN_ASSIST} TASK10_POUR_RETURN_ASSIST_TARGET_RADIUS=${TASK10_POUR_RETURN_ASSIST_TARGET_RADIUS} TASK10_POUR_RETURN_ASSIST_ROTATION_MAGNITUDE=${TASK10_POUR_RETURN_ASSIST_ROTATION_MAGNITUDE} TASK10_POUR_RETURN_ASSIST_MAX_STEPS=${TASK10_POUR_RETURN_ASSIST_MAX_STEPS} ORACLE_TASK8_PICK_AFTER_PLACE_STEPS=${ORACLE_TASK8_PICK_AFTER_PLACE_STEPS} PORT=${PORT} RUN_ID=${RUN_ID} OUT_ROOT=${OUT_ROOT} RUNTIME_HOME=${RUNTIME_HOME} bash ${PACK_DIR}/scripts/run_autonomous_task.sh 2>&1 | tee ${SUBMIT_LOG}'"

echo "session=${SESSION}"
echo "job_name=${JOB_NAME}"
echo "partition=${PARTITION}"
echo "node=${NODE:-scheduler}"
echo "run_id=${RUN_ID}"
echo "vla_policy_seed=${VLA_POLICY_SEED}"
echo "vlm_interval=${VLM_INTERVAL}"
echo "hold_after_required_stages=${HOLD_AFTER_REQUIRED_STAGES}"
echo "stage_latch_autonomous_hold=${STAGE_LATCH_AUTONOMOUS_HOLD}"
echo "prompt_no_regression=${PROMPT_NO_REGRESSION}"
echo "pour_return_assist=${POUR_RETURN_ASSIST}"
echo "pour_return_assist_target_radius=${POUR_RETURN_ASSIST_TARGET_RADIUS}"
echo "pour_return_assist_rotation_magnitude=${POUR_RETURN_ASSIST_ROTATION_MAGNITUDE}"
echo "pour_return_assist_max_steps=${POUR_RETURN_ASSIST_MAX_STEPS}"
echo "task10_pour_return_assist=${TASK10_POUR_RETURN_ASSIST}"
echo "task10_pour_return_assist_target_radius=${TASK10_POUR_RETURN_ASSIST_TARGET_RADIUS}"
echo "task10_pour_return_assist_rotation_magnitude=${TASK10_POUR_RETURN_ASSIST_ROTATION_MAGNITUDE}"
echo "task10_pour_return_assist_max_steps=${TASK10_POUR_RETURN_ASSIST_MAX_STEPS}"
echo "oracle_task8_pick_after_place_steps=${ORACLE_TASK8_PICK_AFTER_PLACE_STEPS}"
echo "replan_steps=${REPLAN_STEPS}"
echo "post_stage_steps=${POST_STAGE_STEPS}"
echo "out_root=${OUT_ROOT}"
echo "submit_log=${SUBMIT_LOG}"
echo "mem_mb=${MEM_MB}"
tmux ls | grep -F "${SESSION}"
