#!/usr/bin/env bash
set -euo pipefail

PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP=${STAMP:-$(date +%Y%m%d_%H%M%S)}

export MODE=vlm_free
export RUN_ID=${RUN_ID:-mw_orig35999_t21_v108_historicalvlm_eef_latest622_${STAMP}}
export VLM_CKPT=${VLM_CKPT:?set VLM_CKPT to the Task21 v121 VLM checkpoint}
export NUM_TRIALS=${NUM_TRIALS:-1}
export SEED=${SEED:-107}
export MAX_STEPS=${MAX_STEPS:-2000}
export REPLAN_STEPS=${REPLAN_STEPS:-5}

# Prompts remain VLM-generated. Official completed stages are input context and
# anti-regression evidence only; no next prompt is injected.
export VLM_COMPLETED_SUBTASKS_MODE=completed_struct
export COMPLETED_UPDATE_FROM_OFFICIAL_STAGE=1
export VLM_HOLD_STATE_HINT=1
export VLM_HOLD_STATE_HINT_PHASE=active
export BLOCK_FORWARD_BEFORE_FIRST_STAGE_DONE=1
export MICROWAVE_STAGE_LOCK_UNTIL_DONE=0
export MICROWAVE_FORWARD_REQUIRE_PRIOR_HOLD=0
export REQUIRE_HOLD_RELEASE_FOR_PICK_FORWARD=1
export REQUIRE_HOLD_RELEASE_FOR_PICK_FORWARD_SUBTASKS="pick butter,pick chocolate"
export REQUIRE_HOLD_RELEASE_FOR_PLACE_FORWARD=1
export PREVENT_COMPLETED_STAGE_REGRESSION=1
export PREVENT_HELD_SUBTASK_REGRESSION=1
export PREVENT_RELEASED_HOLD_REGRESSION=0
export PREVENT_SUBTASK_REGRESSION=0
export REGRESSION_GUARD_AFTER_HOLD_RELEASE=0
export FORWARD_SWITCH_BLOCK_PREVIOUS=0
export HOLD_RELEASE_BLOCK_PAST_SUBTASKS=0

export ORACLE_HOLD_RELEASE_NEXT=0
export ORACLE_FORCE_INITIAL_PROMPT=0
export ORACLE_INITIAL_STAGE_LOCK=0
export ORACLE_STAGE_ADVANCE_NEXT=0
export ORACLE_MONOTONIC_SEQUENCE_LOCK=0
export ORACLE_STAGE_LOCK_UNTIL_DONE=0
export REQUIRE_INITIAL_VLM_SUBTASK=0
export STRICT_HOLD_RELEASE_NEXT=0

# EEF-only holds. The demonstrated pick target has two passages: approach and
# post-grasp lift. Requiring the second passage avoids interrupting the grasp.
export ENDPOSE_PLACE_OBJECT_GATE_JSON=
export ENDPOSE_PICK_OBJECT_LIFT_GATE=0
export ENDPOSE_PICK_OBJECT_LIFT_GATE_BY_SUBTASK_JSON='{}'
export ENDPOSE_PICK_HEIGHT_REQUIRE_EEF_NEAR=0
export ENDPOSE_PICK_GRIPPER_GATE=0
export ENDPOSE_PICK_DEFERRED_GRIPPER_RELEASE=0
export ENDPOSE_HOLD_TARGETS_JSON=${ENDPOSE_HOLD_TARGETS_JSON:-${PACK_DIR}/config/tasks2_26_endpose_targets_seed100_199.json}
export ENDPOSE_TARGET_PASSAGE_COUNTS_JSON=${ENDPOSE_TARGET_PASSAGE_COUNTS_JSON:-${PACK_DIR}/config/tasks2_26_target_passage_counts_seed100_199_alltasks_tol045_20260624_074452.json}
export ENDPOSE_HOLD_POS_TOL_BY_SUBTASK_FILE=${ENDPOSE_HOLD_POS_TOL_BY_SUBTASK_FILE:-${PACK_DIR}/config/task21_eef_open105_pick045_place060_tol_20260718.json}
# Keep a task-specific caller override. The v121 wrapper supplies its frozen
# min-hold config; only legacy callers should use the historical default.
export ENDPOSE_HOLD_RELEASE_MIN_STEPS_BY_SUBTASK_FILE=${ENDPOSE_HOLD_RELEASE_MIN_STEPS_BY_SUBTASK_FILE:-${PACK_DIR}/config/task21_eef_runtime_pickplace_hold30_20260718.json}
export ENDPOSE_HOLD_CONSECUTIVE_BY_SUBTASK_JSON='{"open microwave":1,"place butter":3,"place chocolate":3}'
export ENDPOSE_HOLD_START_AFTER_RELEASE_ANCHOR=1
export ENDPOSE_HOLD_START_AFTER_RELEASE_ANCHOR_SUBTASKS="pick butter,pick chocolate"

export SUBTASK_RELEASE_ANCHORS_JSON=${SUBTASK_RELEASE_ANCHORS_JSON:-${PACK_DIR}/config/release_anchors_t21_t23_openpick_robotonly.json}
export INITIAL_SUBTASK_ANCHORS_JSON=
export ALLOW_STAGE_DONE_RELEASE_ANCHOR=0
export ALLOW_AUTONOMOUS_FORWARD_RELEASE_ANCHOR=0
export POST_HOLD_RELEASE_VLA_STEPS=50
export POST_HOLD_RELEASE_VLA_STEPS_BY_SUBTASK_JSON='{}'
export POST_PICK_HOLD_RELEASE_SAME_PROMPT_STEPS=${POST_PICK_HOLD_RELEASE_SAME_PROMPT_STEPS:-0}
export ENDPOSE_HOLD_AUTO_RESUME_SAME_PROMPT=0
export REQUIRE_OPEN_MICROWAVE_ENDPOSE_HOLD_BEFORE_RELEASE=1
export MICROWAVE_REQUIRE_OPEN_EEF_HOLD_FOR_SUCCESS=1
export MICROWAVE_DEBUG_SAVE_VLM_FRAMES=1
export STOP_ON_STAGE_SUCCESS=1

export REPRO_SNAPSHOT_HELPER=${REPRO_SNAPSHOT_HELPER:-${PACK_DIR}/scripts/snapshot_task21_v121.sh}
export REQUIRE_REPRO_SNAPSHOT=${REQUIRE_REPRO_SNAPSHOT:-1}
export REPRO_ENTRY_LAUNCHER=${REPRO_ENTRY_LAUNCHER:-${BASH_SOURCE[0]}}

exec bash "${PACK_DIR}/scripts/run_microwave_eefonly_no_object_gate.sh" 21
